INSERT INTO `products_brand` VALUES 
(14,'Alpeda','brand_images/alpeda.jpg','alpeda'),
(15,'Nilo','brand_images/nilo.jpg','nilo'),
(16,'Cala','brand_images/cala.jpg','cala'),
(17,'Alter Ego','brand_images/alter-ego.jpg','alter-ego'),
(18,'American Crew','brand_images/american-crew.jpg','american-crew'),
(19,'Andis','brand_images/andis.jpg','andis'),
(20,'Ardell','brand_images/ardell.jpg','ardell'),
(21,'Argila','brand_images/argila.jpg','argila'),
(22,'Artecno','brand_images/artecno.jpg','artecno'),
(23,'Babylisspro','brand_images/babylisspro.jpg','babylisspro'),
(24,'Btoxx','brand_images/btoxx.jpg','btoxx'),
(25,'Cellutec','brand_images/cellutec.jpg','cellutec'),
(26,'Elchim','brand_images/elchim.jpg','elchim'),
(27,'Enercos','brand_images/enercos.jpg','enercos'),
(28,'Footspa','brand_images/footspa.jpg','footspa'),
(29,'Gena','brand_images/gena.jpg','gena'),
(30,'GHD','brand_images/ghd.jpg','ghd'),
(31,'Home Beauty','brand_images/homebeauty.jpg','homebeauty'),
(32,'Keratin Complex','brand_images/keratin-complex.jpg','keratin-complex'),
(33,'Cover Your Gray','brand_images/cover-your-gray.jpg','cover-your-gray'),
(34,'Dare To Wear','brand_images/dare-to-wear.jpg','dare-to-wear'),
(35,"Dr. B's",'brand_images/dr-bs.jpg','dr-bs'),
(36,'Ensyline','brand_images/ensyline.jpg','ensyline'),
(37,'Gelee','brand_images/gelee.jpg','gelee'),
(38,'HSA','brand_images/hsa.jpg','hsa'),
(39,'Le Chat','brand_images/lechat.jpg','lechat'),
(40,'Maletti','brand_images/maletti.jpg','maletti'),
(41,'Marianna','brand_images/marianna.jpg','marianna'),
(42,'Moda','brand_images/moda.jpg','moda'),
(43,'Nail Architecture','brand_images/nail-architecture.jpg','nail-architecture'),
(44,'Nubian Heritage','brand_images/nubian-heritage.jpg','nubian-heritage'),
(45,'Olivia Garden','brand_images/olivia-garden.jpg','olivia-garden'),
(46,'Organic Keragen','brand_images/organic-keragen.jpg','organic-keragen'),
(47,'Oyster','brand_images/oyster.jpg','oyster'),
(48,'Pro Nail','brand_images/pro-nail.jpg','pro-nail'),
(49,'Pro Sheen','brand_images/pro-sheen.jpg','pro-sheen'),
(50,'Pure Organics','brand_images/pure-organics.jpg','pure-organics'),
(51,'Shea Moisture','brand_images/shea-moisture.jpg','shea-moisture'),
(52,'Sparedi','brand_images/sparedi.jpg','sparedi'),
(53,'Sterex','brand_images/sterex.jpg','sterex'),
(54,'The Carlton','brand_images/the-carlton.jpg','the-carlton');
