INSERT INTO `products_product` (name, subcategory_id, code, image, description, slug, date_created) VALUES 
('Blitz HT',9,'E22041HT','product_images/blitz-ht.jpg',"Vaporizer for professional aesthetic treatments curative. Blitz Super electronic timer, electronic temperature control and quantity of steam, water refill indicator, operation indicator and condensate tank.",'blitz-ht',NOW()),
('Blitz 01',9,'E22041','product_images/blitz-01.jpg',"Vaporizer for professional aesthetic treatments curative. Blitz Super electronic timer, electronic temperature control and quantity of steam, water refill indicator, operation indicator and condensate tank.",'blitz-01',NOW()),
('Wall Arms',10,NULL,'product_images/wall-arms.jpg','','wall-arms',NOW()),
('Ozone C5000',11,NULL,'product_images/ozone-c5000.jpg',"The real evolution in the hairdresser salon. Sophisticated design and innovative air vents that allow a more accurate process control treatments. C5000 is: Display LCD touch screen 6 inches with innovative ""friend"", multi-language menu with icons and speaker",'ozone-c5000',NOW()),
('CIX3000 HT',11,NULL,'product_images/cix3000-ht-01.jpg',"Termostimolatore compact and functional combining attractive design and maximum comfort for the client. Top performance in its class, allows you to perform any work in half the time always with the best results.",'cix3000-ht',NOW()),
('CIX3000',11,NULL,'product_images/cix3000-01.jpg',"Termostimolatore compact and functional combining attractive design and maximum comfort for the client. Top performance in its class, allows you to perform any work in half the time always with the best results.",'cix3000',NOW()),
('Champion',12,NULL,'product_images/champion-01.jpg',"A particular attention to design and fashion. Elegant and balanced forms adopts aesthetic finishes SOFT-TOUCH system that combined with HPS and low weight allow easy operation, dynamic and versatile for all your needs",'champion',NOW()),
('Diamante',13,NULL,'product_images/diamante-01.jpg',"Hood dryer for professional hairdressers. Diamond 3000 - Automatic with timer, thermostat, indicator light and temperature indicator light.",'diamante',NOW()),
('Diffusori',12,NULL,'product_images/diffusori.jpg','Accessary','diffusori',NOW()),
('DJ 3600',12,NULL,'product_images/dj-3600-01.jpg',"Hairdryer DJ 3600 Ceriotti ""YOUNG"". New, elegant, sinuous, particularly balanced and lightweight with less than 480 grams of weight. Aesthetic finishes with effects on the carbon fiber, satin finishing and light strokes.",'dj-3600',NOW());
